import os
import tarfile
import typing as t

import numpy as np
import pandas as pd

from pyfm import utils

from pyfm.dataio.converter import frame_to_dict

dataFrameFn = t.Callable[[np.ndarray], pd.DataFrame]
loadFn = t.Callable[[str, t.Dict], pd.DataFrame]


def write(
    df: pd.DataFrame,
    filestem: str,
    write_fn: t.Callable[[pd.DataFrame, str], None],
    tar: str | None = None,
) -> None:
    """
    Writes the data from a DataFrame to one or more files based on the given format and specified write function.

    Parameters:
    df (pd.DataFrame): The input DataFrame containing the data to be written.
    filestem (str): A filename format string that may include placeholders for column values.
    write_fn (Callable[[pd.DataFrame, str], None]): A callable function responsible for writing each portion of the DataFrame to a file,
    taking the specific DataFrame segment and file path as arguments.
    tar (str | None): If provided, bundles all output files into a tar archive at this path and removes the originals.

    Behavior:
    - If the `filestem` contains placeholders (keys enclosed in `{}`) that match column names in the DataFrame:
        - Validates that the DataFrame is non-empty and that all placeholder keys exist in the DataFrame columns.
        - Groups the DataFrame by the placeholder keys and writes each group to a separate file.
          The filename for each group is generated by replacing the placeholders in `filestem` with the corresponding group values.
        - The columns used for creating the groups are excluded from the output file, ensuring only the remaining columns are written.
    - If the `filestem` does not contain placeholders:
        - Writes the entire DataFrame to a single file using the specified `filestem` as the filename.
    - Creates the necessary directories for the output files if they do not already exist.
    - If `tar` is specified, all written files are bundled into a tar archive at that path and the originals are removed.
    """
    fs = os.path.expanduser(filestem)
    repl_keys: t.List[str] = utils.string.format_keys(fs)
    logger = utils.get_logger()
    written_files: t.List[str] = []

    if repl_keys:
        logger.debug(f"df columns: {df.columns}")
        logger.debug(f"df indices: {df.index.names}")
        assert len(df) != 0
        assert all([k in df.columns for k in repl_keys])

        for group, df_group in df.groupby(by=repl_keys):
            repl_vals: t.Tuple[str] = (group,) if isinstance(group, str) else group

            repl = dict(zip(repl_keys, repl_vals))

            filename = fs.format(**repl)
            logger.info(f"Writing file: {filename}")

            if directory := os.path.dirname(filename):
                os.makedirs(directory, exist_ok=True)

            out_cols = [c for c in df_group.columns if c not in repl_keys]

            write_fn(df_group[out_cols], filename)
            written_files.append(filename)

    else:
        filename = fs
        logger.info(f"Writing file: {filename}")
        if directory := os.path.dirname(filename):
            os.makedirs(directory, exist_ok=True)

        write_fn(df, fs)
        written_files.append(filename)

    if tar is not None:
        tar_path = os.path.expanduser(tar)
        if directory := os.path.dirname(tar_path):
            os.makedirs(directory, exist_ok=True)
        logger.info(f"Bundling {len(written_files)} file(s) into tar: {tar_path}")
        with tarfile.open(tar_path, "w") as tf:
            for f in written_files:
                tf.add(f, arcname=os.path.basename(f))
        for f in written_files:
            os.remove(f)


def write_files(
    df: pd.DataFrame, filestem: str, *, format: str | None = None, tar: str | None = None, **kwargs
) -> None:
    # Determine output file format from parameter or filestem extension
    stem, ext = os.path.splitext(filestem)
    match ext:
        case ".h5":
            format = format or "hdf5"
        case ".csv":
            format = format or "csv"
        case ".parquet":
            format = format or "parquet"
        case ".npy" | ".p":
            format = format or "dict"
        case _:
            if format is None:
                raise ValueError(
                    f"No valid format given for writing to file: {filestem}."
                )

    if format == "csv":
        out_filestem = stem + ".csv"
        fn = lambda data, fname: data.to_csv(fname)
    elif format == "hdf5":
        out_filestem = stem + ".h5"
        fn = lambda data, fname: data.to_hdf(fname, key="corr", mode="w")
    elif format == "parquet":
        try:
            import pyarrow  # noqa: F401
        except ImportError:
            raise NotImplementedError(
                "Parquet support requires pyarrow. Install with: pip install pyfm[parquet]"
            )
        out_filestem = stem + ".parquet"
        fn = lambda data, fname: data.to_parquet(fname)
    elif format == "dict":
        dict_depth = kwargs.pop("dict_depth", 1)
        out_filestem = stem
        def fn(data, fname):
            np.save(fname, frame_to_dict(data, dict_depth))
    else:
        raise NotImplementedError(f"No support for format {format}.")

    write(df, out_filestem, write_fn=fn, tar=tar)
