import os
import typing as t

import numpy as np
import pandas as pd

from pyfm import utils

from pyfm.dataio.converter import frame_to_dict

dataFrameFn = t.Callable[[np.ndarray], pd.DataFrame]
loadFn = t.Callable[[str, t.Dict], pd.DataFrame]


def write(
    df: pd.DataFrame, filestem: str, write_fn: t.Callable[[pd.DataFrame, str], None]
) -> None:
    """
    Writes the data from a DataFrame to one or more files based on the given format and specified write function.

    Parameters:
    df (pd.DataFrame): The input DataFrame containing the data to be written.
    filestem (str): A filename format string that may include placeholders for column values.
    write_fn (Callable[[pd.DataFrame, str], None]): A callable function responsible for writing each portion of the DataFrame to a file,
    taking the specific DataFrame segment and file path as arguments.

    Behavior:
    - If the `filestem` contains placeholders (keys enclosed in `{}`) that match column names in the DataFrame:
        - Validates that the DataFrame is non-empty and that all placeholder keys exist in the DataFrame columns.
        - Groups the DataFrame by the placeholder keys and writes each group to a separate file.
          The filename for each group is generated by replacing the placeholders in `filestem` with the corresponding group values.
        - The columns used for creating the groups are excluded from the output file, ensuring only the remaining columns are written.
    - If the `filestem` does not contain placeholders:
        - Writes the entire DataFrame to a single file using the specified `filestem` as the filename.
    - Creates the necessary directories for the output files if they do not already exist.
    """
    fs = os.path.expanduser(filestem)
    repl_keys: t.List[str] = utils.string.format_keys(fs)
    logger = utils.get_logger()
    if repl_keys:
        logger.debug(f"df columns: {df.columns}")
        logger.debug(f"df indices: {df.index.names}")
        assert len(df) != 0
        assert all([k in df.columns for k in repl_keys])

        for group, df_group in df.groupby(by=repl_keys):
            repl_vals: t.Tuple[str] = (group,) if isinstance(group, str) else group

            repl = dict(zip(repl_keys, repl_vals))

            filename = fs.format(**repl)
            logger.info(f"Writing file: {filename}")

            if directory := os.path.dirname(filename):
                os.makedirs(directory, exist_ok=True)

            out_cols = [c for c in df_group.columns if c not in repl_keys]

            write_fn(df_group[out_cols], filename)

    else:
        filename = fs
        logger.info(f"Writing file: {filename}")
        if directory := os.path.dirname(filename):
            os.makedirs(directory, exist_ok=True)

        write_fn(df, fs)


def write_dict(df: pd.DataFrame, filestem: str, dict_depth: int) -> None:
    """
    Writes a pandas DataFrame to a dictionary file format.

    Parameters:
    df: pd.DataFrame
        The input pandas DataFrame to be written.
    filestem: str
        The base name for the output file.
    dict_depth: int
        The depth of the dictionary structure to be created.

    See frame_to_dict for details on conversion from DataFrame to dictionary.
    """

    def writeconvert(data, fname):
        np.save(fname, frame_to_dict(data, dict_depth))

    write(df, filestem, write_fn=writeconvert)


def write_hdf5(df: pd.DataFrame, filestem: str) -> None:
    """
    Writes a DataFrame to a file with a specified filestem using a custom write function.

    Parameters:
    df : pd.DataFrame
        The DataFrame to be written to a file.
    filestem : str
        The base name for the output file.

    See write_data for details.
    """
    write(
        df,
        os.path.splitext(filestem)[0] + ".h5",
        write_fn=lambda data, fname: data.to_hdf(fname, key="corr", mode="w"),
    )


def write_csv(df: pd.DataFrame, filestem: str) -> None:
    """
    Writes a DataFrame to a file with a specified filestem using a custom write function.

    Parameters:
    df : pd.DataFrame
        The DataFrame to be written to a file.
    filestem : str
        The base name for the output file.

    See write_data for details.
    """
    write(
        df,
        os.path.splitext(filestem)[0] + ".csv",
        write_fn=lambda data, fname: data.to_csv(fname),
    )


def write_files(df: pd.DataFrame, format: str, *args, **kwargs) -> None:
    if format == "csv":
        write_csv(df, *args, **kwargs)
    elif format == "hdf5":
        write_hdf5(df, *args, **kwargs)
    elif format == "dict":
        write_dict(df, *args, **kwargs)
    else:
        raise NotImplementedError(f"No support for format {format}.")
